spring:
  application:
    name: gateway
  profiles:
    active: dev
server:
  port: 9999
zuul:
  routes:
    user-service:
      path: /user/**
      serviceId: user-service
    blog-service:
      path: /blog/**
      serviceId: blog-service
hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: THREAD