eureka:
  client:
    service-url:
      defaultZone: http://localhost:1111/eureka
  instance:
    prefer-ip-address: true
spring:
  zipkin:
    base-url: http://localhost:9411/ # SpringBoot默认配置就是此地址
  sleuth:
    sampler:
      probability: 1 # 开发期间收集100%的链路跟踪日志