# 单独：http://localhost:7777/actuator/hystrix.stream
# turbine：http://localhost:8333/turbine.stream
spring:
  application:
    name: user-service
  profiles:
    active: dev
  zipkin:
    base-url: http://localhost:9411/ # SpringBoot默认配置就是此地址
server:
  port: 9000

