spring:
  datasource:
    name: blogDB
    type: org.springframework.jdbc.datasource.DriverManagerDataSource
    url: jdbc:mysql://localhost:3306/db_site
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
