# 同一服务发现内有配置中心的情况下，配置中心的同名配置会覆盖以下配置
spring:
  application:
    name: blog-service
  profiles:
    active: dev
#  cloud:
#    config:
#      profile: dev # 找"blog-service-dev.yml"配置
#    name: blog # 覆盖spring.application.name，来和配置中心交互，否则就找blog-service.yml
#      discovery:
#        enabled: true # 配置中心启用服务发现方式 springCloud2.0在同一个服务发现里，不需要配这个了
#        service-id: config # 配置中心的服务名 springCloud2.0在同一个服务发现里，不需要配这个了
server:
  port: 9001