spring:
  application:
    name: component-gateway
  profiles:
    active: dev
server:
  port: 9999
zuul:
  routes:
    service-user:
      path: /user/**
      serviceId: service-user
    service-blog:
      path: /blog/**
      serviceId: service-blog